### GET ALL Messages
 
GET http://localhost:3000/messages

### Post one message

POST http://localhost:3000/messages
content-type: application/json

{
    "content": "Diamenty white"
}

### Get A particular message
GET http://localhost:3000/messages/575