POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "planbe@vhs.pl",
    "password": "zakaz2115",
    "admin": true
}


### 
GET http://localhost:3000/auth/1

###
GET http://localhost:3000/auth?email=planbe@vhs.pl

###
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "white2115@2115.pl",
    "password": "zakaaz321"
}

###
DELETE http://localhost:3000/auth/1
